### ISSUE TITLE
error message: bad mail configuration

### ISSUE THREAD

**Issue by Pitichinaccio** [MrJohnZoidberg/Snips-Einkaufsliste#1]
Unfortunately I always get the error message: 
"Der Email-Versand ist nicht oder falsch eingerichtet. Bitte schaue in der Beschreibung dieser App nach, wie man den Versand einrichtet"
I entered the email config as shown here, also tried to set the value for PORT also in quotation marks. 
No errors in the syslog, also when calling  "sam service log snips-skill-server".
I get an error when calling "snips-skill-server -vvv":
```
[21:55:46.232825] INFO :snips_skill_server_lib::runner            : [ShoppingList][err]   File "./action-ShoppingList.py", line 71, in <module>
[21:55:46.233070] INFO :snips_skill_server_lib::runner            : [ShoppingList][err]     shoppinglist = ShoppingList(config)
[21:55:46.233152] INFO :snips_skill_server_lib::runner            : [ShoppingList][err]   File "/var/lib/snips/skills/Snips-Einkaufsliste/shoppinglist.py", line 18, in __init__
[21:55:46.233277] INFO :snips_skill_server_lib::runner            : [ShoppingList][err]     io.open(self.shoppinglist_path, 'a').close()  # Create file, if not available
[21:55:46.233468] INFO :snips_skill_server_lib::runner            : [ShoppingList][err] IOError: [Errno 13] Permission denied: '.shoppinglist'
```

bertron

**Comment by dominiczedler** [comment]
Auf Deutsch :-) Die Fehlermeldungen kommen nur, wenn du `snips-skill-server` als Benutzer `pi` startest, denn die Berechtigungen für die Dateien hat ausschließlich der Benutzer `_snips-skills`. D.h. dass bei dem Befehl `sam service log snips-skill-server` keine Fehler kommen, aber mit oben genanntem schon, ist schon richtig so.

Ich habe jetzt nochmal die Fehlermeldung exakter gemacht - jetzt wird entweder angezeigt, dass keine Parameter gefunden wurden (dann ist noch keine Einrichtung geschehen oder das Programm hat die `config.ini` nicht gefunden) oder dass einige Parameter falsch sind/fehlen. Bei letzterer wird in die Logs dann noch reingeschrieben, welche Parameter betroffen sind.

Kannst du bitte diese genauere Fehlermeldung aus dem Log nochmal hier schreiben? Dann weiß ich vielleicht, woran es liegen könnte.

Du musst dazu bloß `sam install skills` ausführen, dann werden die Apps geupdatet und du kannst nochmal versuchen, eine Mail zu versenden.

**Comment by Pitichinaccio** [comment]
Hallo & sorry, daß es ein wenig gedauert hat - war unterwegs.
Habe Dein update installiert, erhalte aber noch immer eine Fehlermeldung:

```
Jan 07 23:07:59 raspberrypi snips-skill-server[1073]: INFO:snips_skill_server_lib::runner: [ShoppingList][out] Fehler: Der Email-Versand ist falsch eingerichtet. Es fehlen notwendige Parameter.
Jan 07 23:07:59 raspberrypi snips-skill-server[1073]: INFO:snips_skill_server_lib::runner: [ShoppingList][out] Fehlende Parameter:
Jan 07 23:07:59 raspberrypi snips-skill-server[1073]: INFO:snips_skill_server_lib::runner: [ShoppingList][out]         ['from', 'password', 'host', 'port', 'to']
```

Die Parameter habe ich exakt wie hier beschrieben eingegeben, die config.ini sieht wie folgt aus:
```
[secret]
email_data="{\"FROM\": \"b......r@gmx.de\", \"PASSWORD\": \"**********\", \"HOST\": \"mail.gmx.net\", \"PORT\": \"587\", \"TO\": \"b......h@gmx.de\"}"
```
Die ganzen "backslashes" stammen dabei allerdings nicht von mir, vielleicht liegt da das Problem?

bertron

**Comment by dominiczedler** [comment]
Mir fällt auf, dass ich in der Anleitung etwas ungenau beschrieben habe. Es ist so, dass ganz außen vorne und hinten eine geschweifte Klammer stehen muss. Wenn man die Anleitung falsch versteht, setzt man vielleicht das ganze Gebilde nochmal in Anführungszeichen. Hast du das auch gemacht?
Weil das ist der Grund, dass da so Backslashes drinnen sind.
Ich werde die Anleitung verbessern und vielleicht auch das Config-Zeug etwas einfacher machen, wenn mir etwas einfällt.

Edit: Oder benutzt du SAM unter Windows? Vielleicht liegt es auch daran.

**Comment by weini22** [comment]
Ich habe leider auch noch Probleme mit dem Emailversand. Zuerst mal würde ich mir noch ein paar zusätzliche Parameter für die Konfiguration wünschen:
USER: <name> FROM und Benutzername (USER) sind nicht immer identisch. Bei meinem Mailserver muss ich z. B. den Benutzernamen ohne Domäne angeben.
STARTTLS: <yes|no> Wenn man einen eigenen Mailserver betreibt, dann ist im lokalen Netz die Verschlüsselung tatsächlich noch nicht "Pflicht".

Du könntest den Login (server.login) abhängig davon machen, ob USER als Parameter vorhanden ist. Ich arbeite tatsächlich im LAN ohne SMPT Authentifizierung.

Aktuell scheitere ich an einer Inkompatibiliät zwischen exim und smtplib:
```
2019-01-07 18:40:07 TLS error on connection from (raspi2) [192.168.0.37] (recv): The TLS connection was non-properly terminated.
2019-01-07 18:40:07 TLS error on connection from (raspi2) [192.168.0.37] (send): The specified session has been invalidated for some reason.

```
Auch deswegen würde ich das STARTTLS gerne ausschalten können.
Ich kann gerne testen, wenn du einen Testbuild hast.

**Comment by Pitichinaccio** [comment]
Hallo,

ja, ich hatte in der Tat den gesamten string in "" gesetzt. Die habe ich jetzt mal aus der config.ini gelöscht, aber die Fehlermeldung bleibt leider. Läuft auf nem Pi, nicht auf Windows. Allerdings habe ich die config.ini unter Win (über winSCP) editiert. Kann es daran liegen? Probiere das gleich nochmal direkt auf dem Pi via Nano.

bertron

**Comment by Pitichinaccio** [comment]
Ich habe die config.ini jetzt nochmal mit nano angeschaut und gespeichert, dann reboot  - keine Änderung. Dann nochmal ein komplettes 
`sam install skills
`
und den config-string  nochmal komplett neu eigegeben, OHNE mit " zu beginnen sondern in den geschw. Klammern.
Die "" und \\ setzt er selber! Jetzt sieht die config.ini nämlich wieder so aus:

```

[secret]
email_data="{\"FROM\": \"b...@gmx.de\", \"PASSWORD\": \"*******\", \"HOST\": \"mail.gmx.net\", \"PORT\": \"587\", \"TO\": \"b......@gmx.de\"}"
```

**Comment by chkuehnel** [comment]
Moin alle, hatte das gleiche Problem. 
Hab die Identifier der Parameter allesamt mit kleinen Buchstaben in der config.ini angegben, dann gehts:
{"from": "meinemail@gmx.net", "password": "eb457fg9", "host": "mail.gmx.net", "port": 587, "to": "meinemail@gmx.net"}

**Comment by Pitichinaccio** [comment]
Aha, Danke für den Hinweis. Bin jetzt schonmal weiter - aber leider noch nicht am Ziel.
Neue Fehlermeldung: `smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out`

**Comment by dominiczedler** [comment]
@weini22 Ich werde die Konfiguration wahrscheinlich vorerst nicht weiter ausbauen, weil es mir zu viel Arbeit im Moment ist. 

@Pitichinaccio Ich schaue mir wenn nötig das in den nächsten Tagen mal an. Ich arbeite hier zum ersten Mal mit der email-Bibliothek in Python und mit den Snips-Config-Problemen kommt da was zusammen...

**Comment by t-h-e-o-p-t-i-m-i-s-t** [comment]
Hallo MrJohnZoidberg,

ich hatte auch das Problem mit Groß-/Kleinschreibung der Email-Config, habe es im Python-Code gefixt und es funktioniert jetzt auich mit groß geschriebenen keys, zumindest bei mir. Habe einen pull request mit dem Fix aufgemacht (hoffe das passt so, bin Neuling bei github :) )

Gruß vom Optimist

**Comment by dominiczedler** [comment]
Ich werde morgen versuchen, es zu mergen oder den Code noch zu verbessern.
Ich muss auch noch die ganzen Apps nach Python 3 portieren, weil es bei vielen Anwendern jetzt eine Fehlermeldung bei der Installation gibt... Und das Snips Team hat die App-Entwicklung erschwert, weil sie irgendwas an den Berechtigungen im Verzeichnis `/var/lib/snips/skills/` geändert haben(meine ich zumindest), sodass ich meine Apps zum Testen nicht mehr lokal per SSH mit `scp files pi@...` übertragen kann.
Mal sehen, wie ich das am besten mache, hab gerade leider wenig Zeit.

**Comment by dominiczedler** [comment]
So, jetzt ist der Patch für die Groß- und Kleinschreibung gemerged (hätte ich auch selber drauf kommen können, dass es daran lag ;) und die App ist nach Python 3 portiert. Wenn neue Probleme auftauchen, bitte einen neuen Issue erstellen.

@weini22  Deine Vorschläge für die anderen Funktionen kann ich nicht so leicht umsetzen, weil ich hier nur die [email](https://docs.python.org/3.5/library/email-examples.html) Library von Python benutze und diese Einstellungsmöglichkeiten habe ich da nicht sehen.
