### ISSUE TITLE
no email data found

### ISSUE THREAD

**Issue by tlrider99** [MrJohnZoidberg/Snips-Einkaufsliste#2]
Hi John,

the app told me that there are no email-data .
Here my config file:
[secret]
email_data=on
{"FROM": "dirk.XXXXXX@gmail.com", "PASSWORD": "XXXXXXXX", "HOST": "smtp.googlemail.com", "PORT": 587, "TO": "tlriXXX@me.com"}
What am I doing wrong?
Thanks a lot 
Dirk

**Comment by dominiczedler** [comment]
I edited the text: https://github.com/MrJohnZoidberg/Snips-Einkaufsliste#iii-configuration

> The content of the config.ini file should look like this:
>
>```
>[secret]
>email_data={"FROM": "meinemail@gmx.net", "PASSWORD": "eb457fg9", "HOST":
>"mail.gmx.com", "PORT": 587, "TO": "hello@gmx.com"}
>```

I hope this works for you. You can open this issue again, if it is still not working.
